name: flutter_project_base
description: Set of interfaces and classes for any flutter project.
version: 0.0.1
repository: https://github.com/bambinoua/flutter_project_base.git

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  charcode: ^1.3.1
  collection: ^1.17.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^11.3.3
  dio: ^4.0.6
  equatable: "2.0.5"
  flutter_bloc: ^9.1.0
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hive_ce: ^2.10.1
  hydrated_bloc: ^10.0.0
  injectable: ^2.4.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  meta: ^1.15.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.2
  universal_html: ^2.2.4
  uuid: ^4.5.0

ignored_advisories:
 - GHSA-4rgh-jx4f-qfcq
 - GHSA-9324-jv53-9cc8
 - GHSA-jwpw-q68h-r678

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
