library flutter_project_base;

export 'package:collection/collection.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:equatable/equatable.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:get_it/get_it.dart' hide Disposable;
export 'package:google_fonts/google_fonts.dart';
export 'package:hydrated_bloc/hydrated_bloc.dart';
export 'package:injectable/injectable.dart';
export 'package:json_annotation/json_annotation.dart';
export 'package:logging/logging.dart';
export 'package:mask_text_input_formatter/mask_text_input_formatter.dart';
export 'package:meta/meta.dart';
export 'package:path_provider/path_provider.dart';
export 'package:provider/provider.dart';
export 'package:rxdart/rxdart.dart';

export 'src/core/authentication.dart';
export 'src/core/basic_types.dart';
export 'src/core/blocs/types.dart' show BlocEvent, BlocState;
export 'src/core/cache.dart';
export 'src/core/constants.dart';
export 'src/core/contracts.dart';
export 'src/core/date.dart';
export 'src/core/domain_driven_design.dart';
export 'src/core/errors.dart';
export 'src/core/exceptions.dart';
export 'src/core/extensions.dart';
export 'src/core/math.dart';
export 'src/data/contracts.dart';
export 'src/data/mapper.dart';
export 'src/data/paging.dart';
export 'src/data/query.dart';
export 'src/material/formfield.dart';
export 'src/material/functions.dart';
export 'src/material/scaffold_messenger.dart' show ScaffoldMessengerOfContext;
export 'src/material/text_input_formatters.dart';
export 'src/material/web/html_view_factory.dart' show DivHtmlElement;
export 'src/material/widgets/internet_connectivity_bar.dart';
export 'src/material/widgets/widgets.dart';
export 'src/services/guid_generator.dart';
export 'src/services/http.dart';
export 'src/services/internet_connectivity.dart';
export 'src/services/logging.dart';
export 'src/services/storage/contracts.dart';
export 'src/services/storage/providers.dart';
export 'src/services/storage/web/providers.dart';
